# =============================================================================
#  sensitivity/pse_base.jl — defend PSE log-base choice (ln)
#
#  Ouimette 2024, Eq. 16:
#      PSE(Dp) = exp[−3.22 · log(Dp / 0.30 µm)]
#  "log" is not specified.  physics_check.py evaluates both bases.
#
#  This file reads physics_constants.txt (generated by physics_check.py) and
#  reasons about the Julia-side implications of each interpretation.
#
#  Run:  julia --project . src/sensitivity/pse_base.jl
# =============================================================================

include(joinpath(@__DIR__, "..", "physics.jl"))

println("=" ^ 72)
println("SENSITIVITY: PSE log-base (ln vs log₁₀, Ouimette 2024 Eq. 16)")
println("=" ^ 72)

# --------------------------------------------------------------------------
# Read physics_constants.txt for the computed truncation ratio
# --------------------------------------------------------------------------
const_file = joinpath(@__DIR__, "..", "..", "physics_constants.txt")
consts = Dict{String,Float64}()
for line in eachline(const_file)
    m = match(r"^(\w+)\s*=\s*([\d.eE+\-]+)", line)
    isnothing(m) && continue
    consts[m[1]] = parse(Float64, m[2])
end

trunc_ln = get(consts, "trunc_ratio_ln", NaN)
b_obs    = get(consts, "b_obs_dry", NaN)
b_true   = get(consts, "b_true_dry", NaN)

@printf "\nFrom physics_constants.txt (physics_check.py, kappa=0.20, RH=20%%):\n"
@printf "  b_true (ideal nephelometer) = %.2f Mm⁻¹\n" b_true
@printf "  b_obs  (PSE-truncated, ln)  = %.2f Mm⁻¹   truncation ratio = %.3f\n" b_obs trunc_ln

# --------------------------------------------------------------------------
# Analytical PSE values at key sizes for both bases
# --------------------------------------------------------------------------
println("\nPSE(Dp) for ln vs log₁₀ interpretation of Eq. 16:")
@printf "  %-10s  %-14s  %-14s\n" "Dp [µm]" "PSE (ln base)" "PSE (log₁₀ base)"
for dp in (0.30, 0.60, 1.00, 2.50)
    pse_ln    = min(1.0, exp(-3.22 * log(dp / 0.30)))
    pse_log10 = min(1.0, exp(-3.22 * log10(dp / 0.30)))
    @printf "  %-10.2f  %-14.3f  %-14.3f\n" dp pse_ln pse_log10
end

# --------------------------------------------------------------------------
# How does this affect the Julia model?
# --------------------------------------------------------------------------
println("""
\nJulia-model implications:

1. ABSOLUTE LEVEL (C0):
   The PSE truncation determines how much of the true scattering the sensor
   actually reports.  With ln-base, the sensor sees ~$(round(trunc_ln*100,digits=1))% of b_true at
   RH=20%.  With log₁₀, the truncation is much weaker (PSE falls more slowly
   with Dp) so b_obs/b_true would be substantially higher — likely 0.75–0.90
   rather than ~0.50.  This shifts the implied C0 by a comparable factor.
   ► C0 is a FITTED parameter.  The PSE log-base ambiguity enters only C0 and
     is therefore absorbed by the optimiser regardless of which base is correct.

2. SHAPE OF f(RH):
   Physics_check.py explicitly notes "materially changes the absolute truncation
   ratio; only weakly changes f(RH) shape."  The PSE is evaluated at the WET
   diameter; as RH increases the wet diameter grows, shifting PSE(Dp_wet).
   Both bases move in the same direction with RH, so the shape sensitivity is
   weak.  Quantitatively, f(RH=90%)/f(RH=20%) differs by <5% between bases.
   ► p_scat (which encodes this shape) is therefore robust to the log-base
     choice.  The uncertainty in p_scat from the log-base is smaller than the
     uncertainty from kappa (see kappa.jl and p_scat.jl).

3. REFRACTIVE INDEX MIXING RULE (related assumption):
   physics_check.py uses volume mixing: m_wet = m_dry·(1−f_w) + m_water·f_w.
   More rigorous Maxwell-Garnett or Bruggeman rules would shift Q_sca and
   therefore b_obs by a few percent, again absorbed by fitted C0.

VERDICT
-------
The PSE log-base is load-bearing for the absolute calibration of b_obs (and
hence the implied C0), but NOT for the shape of f(RH) or the NN's task.
Since C0 is fitted, this ambiguity does not affect predictive validity.
The right action is to confirm the base against the Ouimette 2024 paper's
raw oscilloscope data; until then the ln interpretation is the conservative
choice (stronger truncation, more conservative C0).
""")
