# =============================================================================
#  train_mie_emulator.jl  —  Native Julia training for Layer-1 Mie emulator
#
#  Data:   python_modules/mie_emulator/mie_cache.npz  (generated by Python)
#  Output: mie_emulator_best.jld2  (Julia checkpoint)
#          mie_emulator_frozen.npz  (language-agnostic, compatible with existing
#                                    load_mie_emulator() in mie_emulator.jl)
#
#  Run:  julia --project=. src/train_mie_emulator.jl
#  Opts: julia --project=. src/train_mie_emulator.jl --hidden 512 --layers 8 \
#              --fourier 256 --scale 7.0 --epochs 800 --batch 8192
# =============================================================================

using Lux, Zygote, Optimisers, NPZ, JLD2
using Random, Statistics, Printf

# Load Metal for Apple Silicon GPU unless MIE_USE_METAL=0
if get(ENV, "MIE_USE_METAL", "1") == "1"
    try; @eval using Metal; catch; end
end

const LOGX_CENTER = 0.437f0
const LOGX_HALF   = 3.945f0


# ── Custom Fourier embedding layer ───────────────────────────────────────────
# B lives in `st` (frozen state) — not `ps` (trained parameters).
# This lets Zygote skip B entirely and keeps it out of the optimizer.

struct FourierEmbed <: Lux.AbstractLuxLayer
    n_fourier :: Int
    scale     :: Float32
end

Lux.initialparameters(::AbstractRNG, ::FourierEmbed) = NamedTuple()
Lux.initialstates(rng::AbstractRNG, e::FourierEmbed) =
    (B = randn(rng, Float32, e.n_fourier) .* e.scale,)

function (e::FourierEmbed)(inp::AbstractMatrix, ps, st)
    # inp: (3, N)  rows = [x, n, k]
    x    = inp[1:1, :]
    n    = inp[2:2, :]
    k    = inp[3:3, :]
    logx = log.(x)                                     # (1, N)
    lx_n = (logx .- LOGX_CENTER) ./ LOGX_HALF         # normalised log(x)
    proj = st.B .* vec(logx)'                          # (nf, N)  outer product
    feat = vcat(lx_n, cos.(proj), sin.(proj), n, k)    # (2nf+3, N)
    return feat, st
end


# ── Model factory ─────────────────────────────────────────────────────────────

function build_model(; hidden=512, n_layers=8, n_fourier=256, scale=7.0f0)
    in_dim = 2 * n_fourier + 3
    Chain(
        FourierEmbed(n_fourier, scale),
        Dense(in_dim => hidden, swish),
        [Dense(hidden => hidden, swish) for _ in 1:(n_layers - 1)]...,
        Dense(hidden => 3),   # output: [log(Q_sca), Q_ext, g]  — no activation
    )
end


# ── Loss ──────────────────────────────────────────────────────────────────────
# Log-space MSE on Q_sca (targets already log-transformed in load_data),
# plus light supervision on Q_ext and g.

@inline function mie_loss(model, ps, st, inp, tgt)
    pred, _ = model(inp, ps, st)
    mean((pred[1:1, :] .- tgt[1:1, :]) .^ 2) +
    0.1f0 * mean((pred[2:2, :] .- tgt[2:2, :]) .^ 2) +
    0.1f0 * mean((pred[3:3, :] .- tgt[3:3, :]) .^ 2)
end


# ── Validation ────────────────────────────────────────────────────────────────

function validate(model, ps, st, va_inp, va_tgt)
    pred, _ = model(va_inp, ps, st)
    # Bring to CPU — GPU arrays don't support quantile/sort/boolean indexing
    rel_err = Array(abs.(exp.(pred[1, :] .- va_tgt[1, :]) .- 1f0) .* 100f0)

    x = Array(va_inp[1, :])
    rayleigh  = rel_err[x .< 0.5f0]
    resonance = rel_err[(x .>= 0.5f0) .& (x .<= 30f0)]
    geo       = rel_err[x .> 30f0]

    (
        med       = median(rel_err),
        p99       = quantile(rel_err, 0.99f0),
        rayleigh  = isempty(rayleigh)  ? NaN32 : median(rayleigh),
        resonance = isempty(resonance) ? NaN32 : median(resonance),
        geo       = isempty(geo)       ? NaN32 : median(geo),
    )
end


# ── Batching ──────────────────────────────────────────────────────────────────

function make_batches(inp, tgt, batch_size, rng)
    N   = size(inp, 2)
    idx = randperm(rng, N)
    [(inp[:, idx[i:min(i + batch_size - 1, N)]],
      tgt[:, idx[i:min(i + batch_size - 1, N)]])
     for i in 1:batch_size:N]
end


# ── NPZ export  (compatible with load_mie_emulator() in mie_emulator.jl) ─────

function export_npz(model, ps, st, out_path, arch)
    data = Dict{String, Any}()

    # Fourier frequencies — frozen, stored in state of layer_1 (FourierEmbed)
    data["fourier/B"] = st.layer_1.B

    # Dense layer weights: chain layers 2..end, exported as layers/0..layers/N-1
    n_chain = length(model.layers)
    idx = 0
    for i in 2:n_chain
        sub = getproperty(ps, Symbol("layer_$i"))
        data["layers/$idx/W"] = sub.weight   # (out, in) — same as PyTorch
        data["layers/$idx/b"] = sub.bias
        idx += 1
    end

    data["arch/n_fourier"]      = Int32(arch.n_fourier)
    data["arch/include_logx"]   = Int32(1)
    data["arch/normalize_logx"] = Int32(1)

    npzwrite(out_path, data)
    @printf("Exported → %s  (%d Dense layers)\n", out_path, idx)
end


# ── Main training loop ────────────────────────────────────────────────────────

function train_mie(;
    cache_path  = joinpath(@__DIR__, "..", "python_modules", "mie_emulator", "mie_cache.npz"),
    jld2_path   = joinpath(@__DIR__, "..", "python_modules", "mie_emulator", "mie_emulator_best.jld2"),
    npz_path    = joinpath(@__DIR__, "..", "python_modules", "mie_emulator", "mie_emulator_frozen.npz"),
    hidden      = 512,
    n_layers    = 8,
    n_fourier   = 256,
    scale       = 7.0f0,
    epochs      = 800,
    batch_size  = 8192,
    lr_max      = 3f-4,
    log_every   = 20,
    seed        = 42,
)
    rng = Xoshiro(seed)

    # ── Load data ──────────────────────────────────────────────────────────
    @printf("Loading %s\n", cache_path)
    d = npzread(cache_path)
    tr_inp = Float32.(vcat(d["x_tr"]', d["n_tr"]', d["k_tr"]'))      # (3, N_tr)
    tr_tgt = Float32.(vcat(log.(d["Qsca_tr"])', d["Qext_tr"]', d["g_tr"]'))
    va_inp = Float32.(vcat(d["x_va"]', d["n_va"]', d["k_va"]'))      # (3, N_va)
    va_tgt = Float32.(vcat(log.(d["Qsca_va"])', d["Qext_va"]', d["g_va"]'))
    @printf("Train: %d   Val: %d\n", size(tr_inp, 2), size(va_inp, 2))

    # ── GPU (optional) ─────────────────────────────────────────────────────
    dev = Lux.gpu_device()   # Metal device if `using Metal` was loaded, else CPU
    # tr_inp/tr_tgt stay on CPU — batches are moved to GPU per-step in the loop
    va_inp, va_tgt = va_inp |> dev, va_tgt |> dev   # val forward pass on GPU

    # ── Build model ────────────────────────────────────────────────────────
    arch = (; hidden, n_layers, n_fourier, scale)
    model = build_model(; arch...)
    ps, st = Lux.setup(rng, model)
    ps, st = ps |> dev, st |> dev
    @printf("Model: %d parameters\n", Lux.parameterlength(model))

    # ── Optimizer ──────────────────────────────────────────────────────────
    opt       = Adam(lr_max)
    opt_state = Optimisers.setup(opt, ps)

    best_val_med = Inf32
    t0 = time()

    for epoch in 1:epochs
        # Cosine LR decay: lr_max → 0 over `epochs` steps
        lr = lr_max * 0.5f0 * (1f0 + cos(Float32(π) * (epoch - 1) / epochs))
        Optimisers.adjust!(opt_state, lr)

        epoch_loss = 0f0
        n_batches  = 0
        for (b_inp, b_tgt) in make_batches(tr_inp, tr_tgt, batch_size, Xoshiro(epoch))
            b_inp, b_tgt = b_inp |> dev, b_tgt |> dev
            loss, (gs,) = Zygote.withgradient(ps) do ps
                mie_loss(model, ps, st, b_inp, b_tgt)
            end
            opt_state, ps = Optimisers.update!(opt_state, ps, gs)
            epoch_loss += loss
            n_batches  += 1
        end
        epoch_loss /= n_batches

        if epoch % log_every == 0
            v  = validate(model, ps, st, va_inp, va_tgt)
            dt = time() - t0
            @printf("[%4d/%d] loss=%.4f  med=%.2f%%  p99=%.2f%%  [R=%.2f%% | Res=%.2f%% | G=%.2f%%]  lr=%.2e  t=%.0fs\n",
                    epoch, epochs, epoch_loss, v.med, v.p99, v.rayleigh, v.resonance, v.geo, lr, dt)

            if v.med < best_val_med
                best_val_med = v.med
                # Save Julia checkpoint (full model recoverable)
                jldsave(jld2_path;
                    ps  = ps  |> cpu_device(),
                    st  = st  |> cpu_device(),
                    arch, epoch, val_med = v.med)
                @printf("  → checkpoint saved (best = %.3f%%)\n", best_val_med)
            end
        end
    end

    # ── Final export ───────────────────────────────────────────────────────
    ps_cpu = ps |> cpu_device()
    st_cpu = st |> cpu_device()
    export_npz(model, ps_cpu, st_cpu, npz_path, arch)
    @printf("\nDone. Best val med = %.3f%%\n", best_val_med)

    return model, ps_cpu, st_cpu
end


# ── Checkpoint loader (for downstream use in UDEs etc.) ──────────────────────

"""
    load_mie_model(jld2_path) -> (model, ps, st)

Load a trained Mie emulator from a Julia checkpoint. The returned `model`, `ps`,
`st` can be called directly as `model(inp, ps, st)` and compose with Zygote /
ForwardDiff / SciML solvers without any export step.
"""
function load_mie_model(jld2_path::AbstractString)
    ck = JLD2.load(jld2_path)
    a  = ck["arch"]
    model = build_model(; a.hidden, a.n_layers, a.n_fourier, a.scale)
    @printf("Loaded epoch %d  (val med %.3f%%)\n", ck["epoch"], ck["val_med"])
    return model, ck["ps"], ck["st"]
end


# ── CLI entry point ───────────────────────────────────────────────────────────

if abspath(PROGRAM_FILE) == @__FILE__
    args = Dict(zip(ARGS[1:2:end], ARGS[2:2:end]))
    train_mie(
        hidden     = parse(Int,     get(args, "--hidden",  "512")),
        n_layers   = parse(Int,     get(args, "--layers",  "8")),
        n_fourier  = parse(Int,     get(args, "--fourier", "256")),
        scale      = parse(Float32, get(args, "--scale",   "7.0")),
        epochs     = parse(Int,     get(args, "--epochs",  "800")),
        batch_size = parse(Int,     get(args, "--batch",   "8192")),
        lr_max     = parse(Float32, get(args, "--lr",      "3e-4")),
        log_every  = parse(Int,     get(args, "--log",     "20")),
    )
end
