# =============================================================================
#  train_angular_emulator.jl  —  Native Julia training for Layer-2 angular emulator
#
#  Data:   python_modules/angular_emulator/angular_cache.npz  (generated by Python)
#  Output: angular_emulator_best.jld2   (Julia checkpoint — PRIMARY artifact)
#          angular_emulator_frozen.npz  (language-agnostic export)
#
#  Architecture:
#    Features (computed on CPU, OUTSIDE the Zygote gradient tape):
#      lx_norm           ×1      (normalised log x)
#      cos(Bⱼ·logx)    ×256     (Fourier features on log x)
#      sin(Bⱼ·logx)    ×256
#      P₀(μ)…P₁₀₀(μ)  ×101     (Legendre polynomials on cosθ)
#      n_norm, k_norm    ×2
#      total: 616 features
#    MLP (Metal GPU):
#      Dense(616 → 512, swish) × 8 → Dense(512 → 2)   [log i₁, log i₂]
#
#  Why features are precomputed outside Zygote:
#    Neither the Fourier features (which depend on frozen B, not ps) nor the
#    Legendre features (which depend only on data μ) carry any gradient w.r.t.
#    ps (the Dense-layer weights).  A custom Lux encoder layer that computes
#    these inside withgradient() forces Zygote to compile pullbacks for
#    push!/vcat loops and Metal NamedTuple field access — neither is supported.
#    Moving feature computation to CPU before the gradient tape avoids all of
#    this while being architecturally correct.
#
#  Run:  julia --project=. src/train_angular_emulator.jl
#  Opts: julia --project=. src/train_angular_emulator.jl \
#              --hidden 512 --layers 8 --fourier 256 --scale 7.0 \
#              --legendre 100 --epochs 800 --batch 8192
# =============================================================================

using Lux, Zygote, Optimisers, NPZ, JLD2
using Random, Statistics, Printf

# Julia buffers stdout when redirected to a file; flush after every print so the
# log is readable live (not only at process exit).
pf(fmt::String, args...) = (print(Printf.format(Printf.Format(fmt), args...)); flush(stdout))

if get(ENV, "MIE_USE_METAL", "1") == "1"
    try; @eval using Metal; catch; end
end

const LOGX_CENTER = 0.4365f0
const LOGX_HALF   = 3.9383f0
const N_CENTER    = 1.565f0
const N_HALF      = 0.235f0
const K_CENTER    = 0.40f0
const K_HALF      = 0.40f0
const I_FLOOR     = 1f-15


# ── CPU feature computation (never inside Zygote) ─────────────────────────────

function _legendre_cpu!(out::AbstractMatrix{Float32}, mu::AbstractVector{Float32}, n_max::Int)
    N = length(mu)
    @inbounds for j in 1:N
        out[1, j] = 1f0
        out[2, j] = mu[j]
        for k in 1:(n_max - 1)
            kf = Float32(k)
            out[k+2, j] = ((2f0*kf + 1f0) * mu[j] * out[k+1, j] - kf * out[k, j]) / (kf + 1f0)
        end
    end
end

"""
    compute_features(inp, B, n_legendre) → Matrix{Float32}  shape (2nf+nl+4, N)

Build the full 616-feature input matrix for the MLP from raw (x,n,k,μ) data.
Runs on CPU.  B is the frozen Fourier frequency vector (length n_fourier).
"""
function compute_features(inp::AbstractMatrix{Float32},
                           B  ::AbstractVector{Float32},
                           n_legendre::Int)::Matrix{Float32}
    n_fourier = length(B)
    N         = size(inp, 2)
    feat_dim  = 2 * n_fourier + n_legendre + 4    # 616 for defaults

    x_v  = @view inp[1, :]
    n_v  = @view inp[2, :]
    k_v  = @view inp[3, :]
    mu_v = @view inp[4, :]

    logx = log.(x_v)
    feat = Matrix{Float32}(undef, feat_dim, N)

    # Row 1: normalised log x
    @. feat[1, :] = (logx - LOGX_CENTER) / LOGX_HALF

    # Rows 2:nf+1 and nf+2:2nf+1 — Fourier features on log x
    @inbounds for j in 1:n_fourier
        @. feat[1+j, :]     = cos(B[j] * logx)
        @. feat[1+j+n_fourier, :] = sin(B[j] * logx)
    end

    # Rows 2nf+2:2nf+nl+2 — Legendre polynomials on μ
    leg_view = @view feat[2*n_fourier+2 : 2*n_fourier+n_legendre+2, :]
    _legendre_cpu!(leg_view, collect(mu_v), n_legendre)

    # Rows 2nf+nl+3 and 2nf+nl+4 — normalised n, k
    @. feat[feat_dim-1, :] = (n_v - N_CENTER) / N_HALF
    @. feat[feat_dim,   :] = (k_v - K_CENTER) / K_HALF

    return feat
end


# ── Model (Dense-only — Zygote traces cleanly through matmuls) ────────────────

function build_angular_model(; hidden=512, n_layers=8, in_dim=616)
    Chain(
        Dense(in_dim => hidden, swish),
        [Dense(hidden => hidden, swish) for _ in 1:(n_layers - 1)]...,
        Dense(hidden => 2),
    )
end


# ── Loss ──────────────────────────────────────────────────────────────────────

@inline function angular_loss(model, ps, st, feat, tgt)
    pred, _ = model(feat, ps, st)
    0.5f0 * mean((pred[1:1, :] .- tgt[1:1, :]) .^ 2) +
    0.5f0 * mean((pred[2:2, :] .- tgt[2:2, :]) .^ 2)
end


# ── Validation ────────────────────────────────────────────────────────────────

function validate_angular(model, ps, st, va_feat, va_tgt, va_mu_cpu)
    pred, _ = model(va_feat, ps, st)
    i1_pred = Array(exp.(pred[1, :]))
    i1_true = Array(exp.(va_tgt[1, :]))
    re       = abs.(i1_pred .- i1_true) ./ max.(i1_true, I_FLOOR) .* 100f0
    mu       = va_mu_cpu

    med = median(re)
    p99 = quantile(re, 0.99f0)

    fwd_mask  = mu .> cos(deg2rad(20.0))
    side_mask = (mu .> cos(deg2rad(140.0))) .& (mu .< cos(deg2rad(40.0)))
    back_mask = mu .< cos(deg2rad(160.0))

    med_fwd  = isempty(re[fwd_mask])  ? NaN32 : median(re[fwd_mask])
    med_side = isempty(re[side_mask]) ? NaN32 : median(re[side_mask])
    med_back = isempty(re[back_mask]) ? NaN32 : median(re[back_mask])

    (; med, p99, fwd=med_fwd, side=med_side, back=med_back)
end


# ── Batching ──────────────────────────────────────────────────────────────────

function make_batches(inp, tgt, batch_size, rng)
    N   = size(inp, 2)
    idx = randperm(rng, N)
    [(inp[:, idx[i:min(i+batch_size-1, N)]],
      tgt[:, idx[i:min(i+batch_size-1, N)]])
     for i in 1:batch_size:N]
end


# ── NPZ export ─────────────────────────────────────────────────────────────────

function export_angular_npz(model, ps, B, out_path, arch)
    data = Dict{String, Any}()
    data["fourier/B"]       = B
    data["arch/n_fourier"]  = Int32(arch.n_fourier)
    data["arch/n_legendre"] = Int32(arch.n_legendre)
    data["arch/scale_x"]    = Float32(arch.scale_x)
    data["arch/hidden"]     = Int32(arch.hidden)
    data["arch/n_layers"]   = Int32(arch.n_layers)

    i = 0
    for k in keys(ps)
        sub = getproperty(ps, k)
        data["layers/$i/W"] = sub.weight
        data["layers/$i/b"] = sub.bias
        i += 1
    end
    npzwrite(out_path, data)
    pf("Exported → %s  (%d Dense layers)\n", out_path, i)
end


# ── Main training loop ────────────────────────────────────────────────────────

function train_angular(;
    cache_path = joinpath(@__DIR__, "..", "python_modules",
                          "angular_emulator", "angular_cache.npz"),
    jld2_path  = joinpath(@__DIR__, "..", "python_modules",
                          "angular_emulator", "angular_emulator_best.jld2"),
    npz_path   = joinpath(@__DIR__, "..", "python_modules",
                          "angular_emulator", "angular_emulator_frozen.npz"),
    hidden     = 512,
    n_layers   = 8,
    n_fourier  = 256,
    scale_x    = 7.0f0,
    n_legendre = 100,
    epochs     = 800,
    batch_size = 8192,
    lr_max     = 3f-4,
    log_every  = 20,
    seed       = 42,
)
    rng = Xoshiro(seed)

    # ── Load raw data (CPU) ────────────────────────────────────────────────
    pf("Loading %s\n", cache_path)
    d = npzread(cache_path)

    tr_inp = Float32.(vcat(d["x_tr"]', d["n_tr"]', d["k_tr"]', d["mu_tr"]'))  # (4, N_tr)
    tr_tgt = Float32.(vcat(log.(max.(d["i1_tr"], I_FLOOR))',
                           log.(max.(d["i2_tr"], I_FLOOR))'))
    va_inp = Float32.(vcat(d["x_va"]', d["n_va"]', d["k_va"]', d["mu_va"]'))
    va_tgt = Float32.(vcat(log.(max.(d["i1_va"], I_FLOOR))',
                           log.(max.(d["i2_va"], I_FLOOR))'))
    va_mu  = Float32.(d["mu_va"])

    pf("Train: %d pts   Val: %d pts\n", size(tr_inp, 2), size(va_inp, 2))

    # ── Frozen Fourier frequencies (CPU) ──────────────────────────────────
    B = randn(rng, Float32, n_fourier) .* scale_x   # frozen — saved with model

    # ── Precompute validation features once (CPU → GPU) ───────────────────
    pf("Precomputing validation features...\n")
    dev = Lux.gpu_device()
    va_feat = compute_features(va_inp, B, n_legendre) |> dev
    va_tgt_dev = va_tgt |> dev

    # ── Build model (Dense layers only — no custom encoder) ───────────────
    in_dim = 2 * n_fourier + n_legendre + 4         # 616
    arch   = (; hidden, n_layers, n_fourier, scale_x, n_legendre)
    model  = build_angular_model(; hidden, n_layers, in_dim)
    ps, st = Lux.setup(rng, model)
    ps, st = ps |> dev, st |> dev
    pf("Model: %d parameters  in_dim=%d\n", Lux.parameterlength(model), in_dim)

    # ── Optimizer ─────────────────────────────────────────────────────────
    opt       = Adam(lr_max)
    opt_state = Optimisers.setup(opt, ps)

    best_val_med = Inf32
    t0 = time()

    for epoch in 1:epochs
        lr = lr_max * 0.5f0 * (1f0 + cos(Float32(π) * (epoch - 1) / epochs))
        Optimisers.adjust!(opt_state, lr)

        epoch_loss = 0f0
        n_batches  = 0

        for (b_raw, b_tgt) in make_batches(tr_inp, tr_tgt, batch_size, Xoshiro(epoch))
            # Feature computation on CPU — outside Zygote, no Metal issues
            b_feat    = compute_features(b_raw, B, n_legendre) |> dev
            b_tgt_dev = b_tgt |> dev

            # Gradient only through Dense layer weights (ps) — Zygote traces cleanly
            loss, (gs,) = Zygote.withgradient(ps) do ps
                angular_loss(model, ps, st, b_feat, b_tgt_dev)
            end
            opt_state, ps = Optimisers.update!(opt_state, ps, gs)
            epoch_loss += loss
            n_batches  += 1
        end
        epoch_loss /= n_batches

        if epoch % log_every == 0
            v  = validate_angular(model, ps, st, va_feat, va_tgt_dev, va_mu)
            dt = time() - t0
            pf("[%4d/%d] loss=%.4f  med=%.2f%%  p99=%.2f%%  [fwd=%.2f%% | side=%.2f%% | back=%.2f%%]  lr=%.2e  t=%.0fs\n",
                    epoch, epochs, epoch_loss, v.med, v.p99,
                    v.fwd, v.side, v.back, lr, dt)

            if v.med < best_val_med
                best_val_med = v.med
                jldsave(jld2_path;
                    ps  = ps |> cpu_device(),
                    st  = st |> cpu_device(),
                    B   = B,
                    arch, epoch, val_med = v.med)
                pf("  → checkpoint saved (best = %.3f%%)\n", best_val_med)
            end
        end
    end

    ps_cpu = ps |> cpu_device()
    export_angular_npz(model, ps_cpu, B, npz_path, arch)
    pf("\nDone. Best val med = %.3f%%\n", best_val_med)
    return model, ps_cpu, st |> cpu_device(), B
end


# ── Checkpoint loader ─────────────────────────────────────────────────────────

"""
    load_angular_model(jld2_path) -> (model, ps, st, B, arch)

Load a trained Layer-2 angular emulator.  B (Fourier frequencies) and arch
are returned separately for use with `compute_features` at inference time.
"""
function load_angular_model(jld2_path::AbstractString)
    ck   = JLD2.load(jld2_path)
    a    = ck["arch"]
    in_dim = 2 * a.n_fourier + a.n_legendre + 4
    model  = build_angular_model(; hidden=a.hidden, n_layers=a.n_layers, in_dim)
    pf("Loaded epoch %d  (val med %.3f%%)\n", ck["epoch"], ck["val_med"])
    return model, ck["ps"], ck["st"], ck["B"], a
end


# ── CLI ───────────────────────────────────────────────────────────────────────

if abspath(PROGRAM_FILE) == @__FILE__
    args = Dict(zip(ARGS[1:2:end], ARGS[2:2:end]))
    train_angular(
        hidden     = parse(Int,     get(args, "--hidden",   "512")),
        n_layers   = parse(Int,     get(args, "--layers",   "8")),
        n_fourier  = parse(Int,     get(args, "--fourier",  "256")),
        scale_x    = parse(Float32, get(args, "--scale",    "7.0")),
        n_legendre = parse(Int,     get(args, "--legendre", "100")),
        epochs     = parse(Int,     get(args, "--epochs",   "800")),
        batch_size = parse(Int,     get(args, "--batch",    "8192")),
        lr_max     = parse(Float32, get(args, "--lr",       "3e-4")),
        log_every  = parse(Int,     get(args, "--log",      "20")),
    )
end
