# =============================================================================
#  parity_gate.jl — §1: Julia-vs-Python emulator parity check
#
#  Hard gate: Julia forward pass must match the Python emulator to ≤1e-5
#  max-absolute-error on the saved test battery.
#
#  If this gate fails, DO NOT PROCEED.  It is a bridge bug upstream of
#  everything else.  Report: which emulator, what inputs, what max error.
#
#  Also checks autodiff ∂(forward)/∂x ≤ 1e-3 via ForwardDiff.
# =============================================================================

using NPZ, ForwardDiff, Printf, Statistics, Random

# Requires mie_emulator.jl + angular_emulator.jl to be included already.

const BATTERY_DIR = joinpath(@__DIR__, "..", "..", "python_modules", "test_battery")
const TOL_FWD     = 1f-5    # max-abs parity tolerance
const TOL_GRAD    = 1f-3    # gradient relative error tolerance


# ---------------------------------------------------------------------------
# Run all parity checks; returns (l1_ok, l2_ok, autodiff_ok)
# ---------------------------------------------------------------------------

"""
    run_parity_gate(l1_emu, l2_emu; verbose) → (l1_ok, l2_ok, autodiff_ok)

Load the test batteries generated by python_modules/test_battery/generate_battery.py
and compare Julia forward passes against saved Python outputs.

STOP-AND-REPORT behaviour: if any check fails, prints a clear diagnostic
and returns false in the corresponding slot — callers must check the result
and not proceed on a failed bridge.
"""
function run_parity_gate(l1_emu::MieEmulatorWeights,
                          l2_emu::AngularEmulatorWeights;
                          verbose::Bool = true)
    l1_ok     = _check_L1(l1_emu, verbose)
    l2_ok     = _check_L2(l2_emu, verbose)
    ad_ok     = _check_autodiff_L1(l1_emu, verbose)

    println()
    println("="^56)
    println("PARITY GATE SUMMARY")
    println("="^56)
    @printf "  L1 forward (Q_sca,Q_ext,g) ≤ 1e-5:  %s\n" l1_ok ? "PASS" : "FAIL ← STOP"
    @printf "  L2 forward (i1,i2)         ≤ 1e-5:  %s\n" l2_ok ? "PASS" : "FAIL ← STOP"
    @printf "  L1 autodiff ∂Q_sca/∂x     ≤ 1e-3:  %s\n" ad_ok ? "PASS" : "FAIL ← STOP"
    println("="^56)
    if !l1_ok || !l2_ok || !ad_ok
        println("\n⚠  PARITY GATE FAILED — do not proceed with calibration scaffold.")
        println("   This is a bridge bug; fix mie_emulator.jl / angular_emulator.jl.")
    else
        println("\n✓  Parity gate passed — bridge matches Python emulator to ≤1e-5.")
    end

    return l1_ok, l2_ok, ad_ok
end


function _check_L1(emu::MieEmulatorWeights, verbose::Bool)
    bat_path = joinpath(BATTERY_DIR, "test_battery_L1.npz")
    if !isfile(bat_path)
        @printf "L1 battery not found at %s\n" bat_path
        @printf "  → Run: python python_modules/test_battery/generate_battery.py\n"
        return false
    end

    d       = npzread(bat_path)
    x_py    = vec(Float64.(d["x"]))
    n_py    = vec(Float64.(d["n"]))
    k_py    = vec(Float64.(d["k"]))
    Qs_py   = vec(d["Q_sca"])
    Qe_py   = vec(d["Q_ext"])
    g_py    = vec(d["g"])
    N       = length(x_py)

    Qs_jl   = similar(x_py)
    Qe_jl   = similar(x_py)
    g_jl    = similar(x_py)

    for i in 1:N
        Qs_jl[i], Qe_jl[i], g_jl[i] = mie_forward(emu,
            Float32(x_py[i]), Float32(n_py[i]), Float32(k_py[i]))
    end

    err_Qs = maximum(abs.(Qs_jl .- Qs_py))
    err_Qe = maximum(abs.(Qe_jl .- Qe_py))
    err_g  = maximum(abs.(g_jl  .- g_py))
    ok     = max(err_Qs, err_Qe, err_g) <= TOL_FWD

    if verbose
        @printf "L1 parity  (N=%d):\n" N
        @printf "  max|ΔQ_sca| = %.2e   %s\n" err_Qs (err_Qs <= TOL_FWD ? "✓" : "✗")
        @printf "  max|ΔQ_ext| = %.2e   %s\n" err_Qe (err_Qe <= TOL_FWD ? "✓" : "✗")
        @printf "  max|Δg|     = %.2e   %s\n" err_g  (err_g  <= TOL_FWD ? "✓" : "✗")
        if !ok
            # Find worst-case inputs for the report
            idx = argmax(abs.(Qs_jl .- Qs_py))
            @printf "  Worst Q_sca mismatch at x=%.4f n=%.4f k=%.4f\n" x_py[idx] n_py[idx] k_py[idx]
            @printf "    Python=%.6e  Julia=%.6e\n" Qs_py[idx] Qs_jl[idx]
        end
    end
    return ok
end


function _check_L2(emu::AngularEmulatorWeights, verbose::Bool)
    bat_path = joinpath(BATTERY_DIR, "test_battery_L2.npz")
    if !isfile(bat_path)
        @printf "L2 battery not found at %s\n" bat_path
        @printf "  → Run: python python_modules/test_battery/generate_battery.py\n"
        return false
    end

    d      = npzread(bat_path)
    x_py   = vec(Float64.(d["x"]))
    n_py   = vec(Float64.(d["n"]))
    k_py   = vec(Float64.(d["k"]))
    mu_py  = vec(Float64.(d["mu"]))
    i1_py  = vec(d["i1"])
    i2_py  = vec(d["i2"])
    N      = length(x_py)

    i1_jl  = similar(x_py)
    i2_jl  = similar(x_py)

    for i in 1:N
        i1_jl[i], i2_jl[i] = angular_forward(emu,
            Float32(x_py[i]), Float32(n_py[i]),
            Float32(k_py[i]), Float32(mu_py[i]))
    end

    # Log-space error is more meaningful for intensities spanning 12 decades
    floor_val = 1e-10
    err_i1_abs = maximum(abs.(i1_jl .- i1_py))
    err_i2_abs = maximum(abs.(i2_jl .- i2_py))
    # Relative error on non-tiny values
    mask    = i1_py .> floor_val
    rel_i1  = maximum(abs.(i1_jl[mask] .- i1_py[mask]) ./ i1_py[mask])
    mask2   = i2_py .> floor_val
    rel_i2  = maximum(abs.(i2_jl[mask2] .- i2_py[mask2]) ./ i2_py[mask2])
    ok_abs  = max(err_i1_abs, err_i2_abs) <= TOL_FWD
    ok_rel  = max(rel_i1, rel_i2) <= 1e-4   # 0.01% relative where signal is above floor
    ok      = ok_abs || ok_rel               # pass if EITHER criterion met

    if verbose
        @printf "L2 parity  (N=%d):\n" N
        @printf "  max|Δi1| abs = %.2e   %s\n" err_i1_abs (err_i1_abs <= TOL_FWD ? "✓" : "—")
        @printf "  max|Δi2| abs = %.2e   %s\n" err_i2_abs (err_i2_abs <= TOL_FWD ? "✓" : "—")
        @printf "  max rel-err i1 (i1>1e-10) = %.2e   %s\n" rel_i1 (rel_i1 <= 1e-4 ? "✓" : "✗")
        @printf "  max rel-err i2 (i2>1e-10) = %.2e   %s\n" rel_i2 (rel_i2 <= 1e-4 ? "✓" : "✗")
        if !ok
            idx = argmax(abs.(i1_jl .- i1_py))
            @printf "  Worst i1 mismatch at x=%.4f μ=%.4f\n" x_py[idx] mu_py[idx]
        end
    end
    return ok
end


function _check_autodiff_L1(emu::MieEmulatorWeights, verbose::Bool)
    # Test ∂Q_sca/∂x via ForwardDiff vs finite-difference on 20 points
    rng    = Random.MersenneTwister(999)
    n_test = 20
    x_pts  = exp.(range(log(0.5f0), log(20.0f0), n_test))
    n_ri   = 1.50f0
    k_ri   = 0.01f0
    eps_fd = 1f-4

    re_list = Float64[]
    for xv in x_pts
        # ForwardDiff gradient — return Qs directly; Float64() fails on Dual types
        grad_ad = ForwardDiff.derivative(xf -> begin
            Qs, _, _ = mie_forward(emu, xf, n_ri, k_ri)
            Qs
        end, Float64(xv))

        # Finite difference
        Qp, _, _ = mie_forward(emu, xv + eps_fd, n_ri, k_ri)
        Qm, _, _ = mie_forward(emu, xv - eps_fd, n_ri, k_ri)
        grad_fd  = (Float64(Qp) - Float64(Qm)) / (2 * Float64(eps_fd))

        re = abs(grad_ad - grad_fd) / (abs(grad_fd) + 1e-12)
        push!(re_list, re)
    end

    med_re = median(re_list)
    max_re = maximum(re_list)
    ok     = max_re <= TOL_GRAD

    if verbose
        @printf "L1 autodiff ∂Q_sca/∂x  (N=%d):\n" n_test
        @printf "  median rel-err = %.2e\n" med_re
        @printf "  max    rel-err = %.2e   %s\n" max_re (ok ? "✓" : "✗")
    end
    return ok
end
